// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildInfo } from "./BuildInfo";
import type { PlatformId } from "./PlatformId";

/**
 * Identity of the running application: what it is, and what it is running on.
 *
 * This is the payload behind the About panel and the "copy for a bug report"
 * action, so it is intentionally cheap to produce and free of anything that
 * could fail.
 */
export type AppInfo = { 
/**
 * Name, version and profile of this build.
 */
build: BuildInfo, 
/**
 * Machine-readable identifier of the host platform.
 */
platform: PlatformId, 
/**
 * How users of the host platform normally spell its name.
 */
platformName: string, };
