// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every term the arithmetic produced, for the explanation drawer.
 *
 * ROADMAP.md M4 requires the drawer to show "the arithmetic ... rather than
 * hidden" — this struct is that arithmetic, held rather than recomputed.
 */
export type Breakdown = { 
/**
 * The model's weights at the chosen quantization: `parameters ×
 * bits_per_weight / 8`.
 */
quantizedWeightBytes: number, 
/**
 * The formula's `× 1.1` headroom, shown as its own term rather than
 * folded silently into the weight figure.
 */
overheadBytes: number, 
/**
 * `kv_cache(context_length, layers, heads)` from the ADR's formula.
 */
kvCacheBytes: number, 
/**
 * The sum of the three terms above — what must fit somewhere.
 */
totalRequiredBytes: number, 
/**
 * VRAM this verdict was weighed against; `0` when no GPU memory figure
 * was available (see [`GpuMemory`]).
 */
availableVramBytes: number, 
/**
 * System memory this verdict was weighed against.
 */
availableSystemMemoryBytes: number, 
/**
 * The context length the KV-cache term was computed at.
 */
contextLength: number, };
