// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildProfile } from "./BuildProfile";

/**
 * Identifies the running osstat build.
 *
 * Field names cross the IPC boundary as `camelCase` so the TypeScript side
 * reads naturally without a mapping layer.
 */
export type BuildInfo = { 
/**
 * Package name of the front-end binary, e.g. `osstat`.
 */
name: string, 
/**
 * Semantic version of the release.
 */
version: string, 
/**
 * Profile the binary was compiled with.
 */
profile: BuildProfile, };
