// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which Cargo profile the running binary was compiled with.
 */
export type BuildProfile = "debug" | "release";
