// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timings } from "./Timings";
import type { Usage } from "./Usage";

/**
 * A reply that ended.
 */
export type ChatComplete = { 
/**
 * Which conversation this belongs to.
 */
conversationId: string, 
/**
 * Token counts for the exchange, where the server reported them.
 */
usage: Usage | null, 
/**
 * The last speeds the server reported.
 */
timings: Timings | null, 
/**
 * Whether the user stopped it rather than the model finishing.
 */
stopped: boolean, };
