// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reply that could not be finished.
 */
export type ChatFailure = { 
/**
 * Which conversation this belongs to.
 */
conversationId: string, 
/**
 * What went wrong, in the server's own words where it left any.
 *
 * An out-of-memory message is written to stderr and nowhere else, so a
 * failure that reported only "the stream ended" would throw away the one
 * sentence that explains why.
 */
message: string, };
