// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timings } from "./Timings";

/**
 * More of a reply.
 */
export type ChatToken = { 
/**
 * Which conversation this belongs to.
 */
conversationId: string, 
/**
 * The text to append.
 */
delta: string, 
/**
 * The latest speeds, where the server has reported any yet.
 *
 * Carried on every token rather than only at the end, which is what makes
 * a live tokens/sec readout possible at all.
 */
timings: Timings | null, };
