// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

/**
 * One conversation.
 */
export type Conversation = { 
/**
 * Stable identifier, and the file's stem.
 */
id: string, 
/**
 * What the list shows.
 */
title: string, 
/**
 * The model this conversation was held with.
 */
modelName: string, 
/**
 * Every turn, oldest first.
 */
messages: Array<Message>, };
