// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The CPU installed in the machine.
 */
export type CpuDescription = { 
/**
 * Marketing name, e.g. `AMD Ryzen 9 7950X`.
 */
brand: string, 
/**
 * Vendor string, e.g. `AuthenticAMD`.
 */
vendor: string, 
/**
 * Physical core count, where the platform reports it.
 */
physicalCores: number | null, 
/**
 * Logical core count — the length of [`MetricsSample::cpu_per_core`].
 */
logicalCores: number, 
/**
 * Nominal frequency in MHz, or zero if the platform did not say.
 */
frequencyMhz: number, };
