// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One process worth stopping to think about.
 */
export type CriticalProcess = { 
/**
 * Which OS this entry describes: `windows`, `linux` or `macos`.
 */
platform: string, 
/**
 * Executable name, matched exactly and case-insensitively.
 */
name: string, 
/**
 * Paths this executable legitimately lives at, matched as suffixes.
 */
paths: Array<string>, 
/**
 * What ending it breaks, in words shown to the user.
 */
breaks: string, };
