// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One disk's occupancy at a single instant.
 */
export type DiskSample = { 
/**
 * Index into [`SystemDescription::disks`].
 */
index: number, 
/**
 * Bytes in use.
 */
used: number, 
/**
 * Capacity in bytes. Repeated per tick because removable media change.
 */
total: number, };
