// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskKind } from "./DiskKind";

/**
 * A mounted filesystem.
 *
 * The `index` is this disk's position in [`SystemDescription::disks`], and is
 * how per-tick samples refer back to it.
 */
export type DiskDescription = { 
/**
 * Position in [`SystemDescription::disks`].
 */
index: number, 
/**
 * Device or volume name.
 */
name: string, 
/**
 * Where it is mounted — `C:\` or `/home`.
 */
mountPoint: string, 
/**
 * Filesystem, e.g. `NTFS` or `ext4`.
 */
fileSystem: string, 
/**
 * Spinning, solid state, or unreported.
 */
kind: DiskKind, 
/**
 * Whether the volume is removable.
 */
removable: boolean, };
