// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Breakdown } from "./Breakdown";
import type { Verdict } from "./Verdict";

/**
 * One model, at one quantization, weighed against one machine.
 */
export type FitResult = { 
/**
 * The model this row describes.
 */
modelId: string, 
/**
 * The quantization level this row describes.
 */
quantId: string, 
/**
 * Whether — and how — it fits.
 */
verdict: Verdict, 
/**
 * The arithmetic behind the verdict, for the explanation drawer.
 */
breakdown: Breakdown, };
