// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much VRAM is available to weigh a model against, as it crosses IPC.
 *
 * A flat struct rather than a tagged enum, matching every other `ts-rs`
 * export in this codebase: `present: false` is "no GPU", `present: true`
 * with `vram_bytes: None` is "a GPU is present but its memory is unknown",
 * and `present: true` with a value is a real figure. [`GpuBudget::memory`]
 * turns this into the three-way [`GpuMemory`] the calculator actually
 * reasons over.
 */
export type GpuBudget = { 
/**
 * Whether any GPU was found at all.
 */
present: boolean, 
/**
 * Its VRAM in bytes, where the source could measure or confidently
 * derive it. `None` while `present` is `true` means a GPU exists but
 * `wgpu` could not report its memory — see the module docs.
 */
vramBytes: number | null, };
