// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuKind } from "./GpuKind";
import type { GpuSource } from "./GpuSource";

/**
 * A GPU present in the machine.
 */
export type GpuDevice = { 
/**
 * Position in the probe's device list; per-tick samples index by this.
 */
index: number, 
/**
 * Adapter name as the driver reports it.
 */
name: string, 
/**
 * Vendor name, where it could be resolved.
 */
vendor: string | null, 
/**
 * Graphics backend the adapter was found through, e.g. `Vulkan`.
 */
backend: string | null, 
/**
 * Discrete, integrated, virtual or software.
 */
kind: GpuKind, 
/**
 * Total video memory in bytes, where the source could supply it.
 *
 * Read together with [`GpuDevice::source`]: from `wgpu` this is advertised
 * rather than measured, and on Apple Silicon it is shared system memory.
 */
vramTotal: number | null, 
/**
 * Which probe produced this device, and how far to trust its numbers.
 */
source: GpuSource, };
