// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of device an adapter is.
 */
export type GpuKind = "discrete" | "integrated" | "virtual" | "cpu" | "other";
