// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One GPU's utilisation at a single instant.
 *
 * Every field is optional because only NVML supplies them; a `wgpu`-sourced
 * device yields a sample with nothing but its index, and the UI shows the
 * device without a utilisation chart rather than inventing a zero.
 */
export type GpuSample = { 
/**
 * Index into the device list returned by the probe.
 */
index: number, 
/**
 * Core utilisation as a percentage, `0.0..=100.0`.
 */
utilisation: number | null, 
/**
 * Video memory in use, in bytes.
 */
vramUsed: number | null, 
/**
 * Die temperature in degrees Celsius.
 */
temperatureC: number | null, };
