// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A runtime present on disk.
 */
export type InstalledRuntimeInfo = { 
/**
 * Upstream release tag.
 */
tag: string, 
/**
 * Artifact identifier.
 */
artifactId: string, 
/**
 * Bytes this install occupies.
 */
sizeBytes: number, };
