// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A network interface.
 */
export type InterfaceDescription = { 
/**
 * Position in [`SystemDescription::interfaces`].
 */
index: number, 
/**
 * Interface name, e.g. `Wi-Fi` or `eth0`.
 */
name: string, 
/**
 * Hardware address, formatted for display.
 */
mac: string | null, 
/**
 * Assigned addresses, formatted for display.
 */
addresses: Array<string>, };
