// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One interface's throughput over the tick that just elapsed.
 */
export type InterfaceSample = { 
/**
 * Index into [`SystemDescription::interfaces`].
 */
index: number, 
/**
 * Bytes received per second during the last tick.
 */
rxPerSecond: number, 
/**
 * Bytes transmitted per second during the last tick.
 */
txPerSecond: number, 
/**
 * Bytes received since osstat started watching.
 */
rxTotal: number, 
/**
 * Bytes transmitted since osstat started watching.
 */
txTotal: number, };
