// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What moving the library to a chosen folder would cost.
 */
export type LibraryMovePlan = { 
/**
 * How many downloaded files would move.
 */
files: number, 
/**
 * How many bytes would move.
 */
bytes: number, 
/**
 * Whether every file can be renamed rather than copied — instant against
 * an hour, which is why Settings states it before asking.
 */
sameVolume: boolean, };
