// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FitResult } from "./FitResult";
import type { GpuBudget } from "./GpuBudget";

/**
 * The whole advisor answer for one machine at one context length.
 *
 * The hardware card and the fit matrix are one payload rather than two
 * commands because they have to agree: a matrix computed against a GPU
 * budget the card is not showing is a table whose arithmetic the user
 * cannot check, which is exactly what ADR-008 asks this feature not to be.
 */
export type LlmAdvice = { 
/**
 * The VRAM the matrix was weighed against.
 */
gpu: GpuBudget, 
/**
 * The system memory the matrix was weighed against.
 */
systemMemoryBytes: number, 
/**
 * The context length actually used, after clamping.
 */
contextLength: number, 
/**
 * One row per model per quantization level.
 */
results: Array<FitResult>, };
