// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much detail the log carries.
 *
 * Three settings are offered over `tracing`'s five. `warn` and `error` are
 * always enabled underneath all three — see [`filter_directive`].
 */
export type LogLevel = "info" | "debug" | "verbose";
