// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";
import type { Usage } from "./Usage";

/**
 * One stored turn.
 *
 * Distinct from [`crate::client::Message`], which is the wire shape. Token
 * counts and a stopped flag are presentation state and have no business on a
 * request body.
 */
export type Message = { 
/**
 * Who said it.
 */
role: Role, 
/**
 * What was said.
 */
content: string, 
/**
 * Token counts for this exchange, where the server reported them.
 */
usage: Usage | null, 
/**
 * Whether generation was stopped before the model finished.
 */
stopped: boolean, 
/**
 * Wall-clock seconds the assistant turn took, where it was measured.
 *
 * `None` on a user turn, which takes as long as the person typing it, and
 * on any assistant turn written before this field existed.
 *
 * `#[serde(default)]` is what makes that second case work rather than
 * throw: conversations are files on disk that a user already has, and a
 * missing field must read as "not measured" rather than fail the load and
 * take the whole conversation with it.
 */
elapsedSeconds: number | null, };
