// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";
import type { Usage } from "./Usage";

/**
 * One stored turn.
 *
 * Distinct from [`crate::client::Message`], which is the wire shape. Token
 * counts and a stopped flag are presentation state and have no business on a
 * request body.
 */
export type Message = { 
/**
 * Who said it.
 */
role: Role, 
/**
 * What was said.
 */
content: string, 
/**
 * Token counts for this exchange, where the server reported them.
 */
usage: Usage | null, 
/**
 * Whether generation was stopped before the model finished.
 */
stopped: boolean, };
