// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";
import type { Usage } from "./Usage";

/**
 * One stored turn.
 *
 * Distinct from [`crate::client::Message`], which is the wire shape. Token
 * counts and a stopped flag are presentation state and have no business on a
 * request body.
 */
export type Message = { 
/**
 * Who said it.
 */
role: Role, 
/**
 * What was said.
 */
content: string, 
/**
 * Token counts for this exchange, where the server reported them.
 */
usage: Usage | null, 
/**
 * Whether generation was stopped before the model finished.
 */
stopped: boolean, 
/**
 * Wall-clock seconds the assistant turn took, where it was measured.
 *
 * `None` on a user turn, which takes as long as the person typing it, and
 * on any assistant turn written before this field existed.
 *
 * `#[serde(default)]` is what makes that second case work rather than
 * throw: conversations are files on disk that a user already has, and a
 * missing field must read as "not measured" rather than fail the load and
 * take the whole conversation with it.
 */
elapsedSeconds: number | null, 
/**
 * When this turn was recorded, in milliseconds since the Unix epoch.
 *
 * Milliseconds rather than a formatted string because the format belongs
 * to whoever is reading it: the front end renders this in the viewer's own
 * locale and time zone, which it cannot do from text this crate has
 * already decided the shape of.
 *
 * `None` on any turn written before this field existed, and `#[serde(default)]`
 * for exactly the reason [`Self::elapsed_seconds`] carries it. Also `None`
 * if the system clock is set before 1970 or past the year 292 million,
 * which is a clock problem rather than a reason to refuse to save a
 * message.
 *
 * Declared to the bindings as `number`, as every other 64-bit field here
 * is: `ts-rs` would otherwise write `bigint`, which `JSON.parse` never
 * produces, so the type would describe something the front end can never
 * receive. A millisecond count stays exact in a double until the year
 * 287396.
 */
sentAt: number | null, };
