// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskSample } from "./DiskSample";
import type { GpuSample } from "./GpuSample";
import type { InterfaceSample } from "./InterfaceSample";

/**
 * Everything measured in a single tick.
 *
 * Deliberately free of strings and paths: this is the payload that crosses IPC
 * on every tick, and the names it would otherwise repeat are already in the
 * [`SystemDescription`] the front-end fetched once.
 */
export type MetricsSample = { 
/**
 * Milliseconds since the Unix epoch, for the time axis.
 */
atMs: number, 
/**
 * Total CPU utilisation as a percentage, `0.0..=100.0`.
 */
cpuTotal: number, 
/**
 * Per-logical-core utilisation, same order and length as the CPU
 * description's `logical_cores`.
 */
cpuPerCore: Array<number>, 
/**
 * Physical memory in use, in bytes.
 */
memoryUsed: number, 
/**
 * Physical memory available to new allocations, in bytes.
 */
memoryAvailable: number, 
/**
 * Swap in use, in bytes.
 */
swapUsed: number, 
/**
 * Per-disk occupancy.
 */
disks: Array<DiskSample>, 
/**
 * Per-interface throughput.
 */
interfaces: Array<InterfaceSample>, 
/**
 * Per-GPU utilisation, where the probe could measure it.
 */
gpus: Array<GpuSample>, };
