// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One downloadable GGUF file: a specific model at a specific quantization,
 * pinned by hash.
 *
 * The URL is derived from `repo` and `file` rather than stored, so the host
 * cannot vary per entry — a wider trust surface than this feature needs, and
 * one nobody would notice widening.
 *
 * `publisher` is recorded because these are community re-quantizations rather
 * than the model vendors' own uploads. Llama and Gemma are gated on Hugging
 * Face, and pinning the official repositories would mean nothing downloads
 * without an account and a stored token. Trusting a third-party re-quantiser
 * is a real trade, so the UI names who published every file rather than
 * presenting a re-upload as though it were the vendor's own.
 */
export type ModelDownload = { 
/**
 * The [`QuantLevel::id`] this file is a build of, e.g. `Q4_K_M`.
 */
quantId: string, 
/**
 * Hugging Face repository, e.g. `bartowski/Qwen2.5-7B-Instruct-GGUF`.
 */
repo: string, 
/**
 * Who published the re-quantization, shown beside the download control.
 */
publisher: string, 
/**
 * File name within the repository.
 */
file: string, 
/**
 * SHA256 of the file, lowercase hex. Pinned here rather than fetched
 * alongside the file: a digest from the same origin proves only that the
 * transfer was not corrupted, not that the bytes are the ones anybody
 * reviewed.
 */
sha256: string, 
/**
 * Exact size in bytes, from the Hugging Face API. The free-space check
 * depends on this being real rather than an estimate.
 */
sizeBytes: number, };
