// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelKey } from "./ModelKey";

/**
 * How a download or a move is progressing.
 */
export type ModelProgress = { 
/**
 * The cell being downloaded, or `None` while the whole library moves.
 */
key: ModelKey | null, 
/**
 * What is happening: `downloading` or `moving`.
 */
phase: string, 
/**
 * Bytes transferred so far, counting anything a resumed download already
 * had, or a resume appears to start over.
 */
downloadedBytes: number, 
/**
 * Bytes expected in total, from the pin rather than from any response.
 */
totalBytes: number, };
