// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What opening a model produced.
 *
 * Deliberately five fields. The base URL, the port and the API key are all
 * absent: the webview has no use for any of them and no way to be trusted
 * with them.
 */
export type ModelSession = { 
/**
 * The model file's name, without its directory or extension.
 */
modelName: string, 
/**
 * Layers offloaded to the GPU — what `-ngl` was given.
 */
gpuLayers: number, 
/**
 * The context window the server actually allocated.
 */
contextLength: number, 
/**
 * Whether every layer fitted. `false` is a warning, never a refusal.
 */
fits: boolean, 
/**
 * Whether the KV-cache arithmetic rested on a derived head dimension.
 *
 * Travels to the UI because a derived figure is right for standard
 * attention and wrong for models that diverge, and a mis-sized cache is
 * otherwise a mystery rather than a diagnosis.
 */
headDimDerived: boolean, };
