// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelEntry } from "./ModelEntry";
import type { QuantLevel } from "./QuantLevel";

/**
 * The whole registry: quantization levels once, models many times.
 */
export type ModelRegistry = { 
/**
 * Bumped whenever the shape of this file changes.
 */
version: number, 
/**
 * Quantization levels every model is priced at.
 */
quantLevels: Array<QuantLevel>, 
/**
 * The models themselves.
 */
models: Array<ModelEntry>, };
