// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelKey } from "./ModelKey";

/**
 * One fit-matrix cell that has a pinned file, a downloaded one, or both.
 *
 * The catalogue is a join, not a copy of the registry: a cell with no entry
 * here is one nobody has pinned, which is what lets the advisor say "not
 * pinned" rather than offer a control that fails. The four states the UI
 * renders are therefore *no entry*, plus the three [`Self::state`] can hold.
 */
export type ModelCatalogueEntry = { 
/**
 * Which cell this describes.
 */
key: ModelKey, 
/**
 * What the cell can do: `downloadable`, `downloading`, or `downloaded`.
 */
state: string, 
/**
 * Who published the re-quantization, so provenance is visible on the
 * control rather than only in the manifest.
 *
 * `None` only for a cell that is downloaded but no longer pinned, which
 * happens when a pin is withdrawn after someone fetched it.
 */
publisher: string | null, 
/**
 * The Hugging Face repository the file comes from.
 */
repo: string | null, 
/**
 * The file name within that repository.
 */
file: string | null, 
/**
 * What the file weighs, from the pin or from the record.
 */
sizeBytes: number, 
/**
 * Where the file is, once it has been downloaded.
 *
 * This is what the Run control hands to `chat_open_model`, so there is one
 * path into a session rather than two.
 */
path: string | null, };
