// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelKey } from "./ModelKey";
import type { Stop } from "./Stop";

/**
 * A download or a move that could not be finished.
 */
export type ModelFailure = { 
/**
 * The cell that failed, or `None` when a move failed.
 */
key: ModelKey | null, 
/**
 * What went wrong, in a sentence the user can act on.
 */
message: string, 
/**
 * Whether offering a retry makes sense.
 *
 * False for a checksum mismatch above all: retrying a hash that did not
 * match either wastes a multi-gigabyte download or invites the user to
 * keep trying until a tampered file slips through.
 */
retryable: boolean, 
/**
 * Whether this was a verification failure rather than a transport one.
 *
 * The UI says something different for these: a mismatch is a security
 * event, not a bad day on the network.
 */
verificationFailure: boolean, 
/**
 * How the user stopped it, or `None` if something actually went wrong.
 *
 * One field rather than a `cancelled` flag and a `paused` flag beside it,
 * because two booleans would spell a state that cannot happen — paused but
 * not stopped — and the UI would have to decide what to render for it.
 */
stopped: Stop | null, };
