// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which cell of the fit matrix a file belongs to.
 */
export type ModelKey = { 
/**
 * The model id from `osstat-llm`'s registry, e.g. `qwen2.5-7b`.
 */
modelId: string, 
/**
 * The quantization id, e.g. `Q4_K_M`.
 */
quantId: string, };
