// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The architectural dimensions the KV-cache formula needs.
 *
 * `hidden_size` is kept for documentation even though the calculator never
 * reads it directly — the cache scales with `head_dim` and `num_kv_heads`,
 * which do not always divide evenly out of `hidden_size` (Gemma 2's `head_dim`
 * of 256 is wider than `hidden_size / num_attention_heads` on the 9B and 2B
 * variants), so both are stored rather than derived.
 */
export type ModelArchitecture = { 
/**
 * Transformer block count (`num_hidden_layers`).
 */
numLayers: number, 
/**
 * Model dimension (`hidden_size`).
 */
hiddenSize: number, 
/**
 * Query head count (`num_attention_heads`).
 */
numAttentionHeads: number, 
/**
 * Key/value head count (`num_key_value_heads`) — equal to
 * `num_attention_heads` on a model with no grouped-query attention.
 */
numKvHeads: number, 
/**
 * Per-head dimension. The KV cache scales with this and `num_kv_heads`.
 */
headDim: number, 
/**
 * The model's native maximum context (`max_position_embeddings`), used
 * to cap the context-length control in the UI.
 */
maxContextLength: number, };
