// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelArchitecture } from "./ModelArchitecture";

/**
 * One model in the registry.
 */
export type ModelEntry = { 
/**
 * Stable slug, used as a React key and to address a row in the fit
 * matrix.
 */
id: string, 
/**
 * Display name.
 */
name: string, 
/**
 * Model family, for grouping in the UI.
 */
family: string, 
/**
 * Total parameter count in billions, as published by the model's own
 * card or technical report.
 */
parametersBillion: number, 
/**
 * The dimensions the KV-cache formula needs.
 */
architecture: ModelArchitecture, 
/**
 * Where the numbers above came from, so a reviewer can check them
 * without re-deriving anything.
 */
sourceNote: string, };
