// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelKey } from "./ModelKey";

/**
 * A download or a move that finished.
 */
export type ModelDone = { 
/**
 * The cell that finished downloading, or `None` when a move finished.
 */
key: ModelKey | null, 
/**
 * The file that landed, or the folder the library moved to.
 */
path: string, };
