// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SocketProtocol } from "./SocketProtocol";
import type { SocketState } from "./SocketState";

/**
 * One port, joined to the process that holds it — the row the front-end
 * renders.
 *
 * A [`SocketRecord`] fans out into one `PortRecord` per entry in
 * [`SocketRecord::pids`], and into exactly one row with `pid: None` when that
 * list is empty, so every socket the probe found is shown exactly once
 * whether it has zero, one, or several owners.
 */
export type PortRecord = { 
/**
 * TCP or UDP.
 */
protocol: SocketProtocol, 
/**
 * The local address this socket is bound to.
 */
localAddress: string, 
/**
 * The local port this socket is bound to.
 */
localPort: number, 
/**
 * The remote peer's address, where there is one.
 */
remoteAddress: string | null, 
/**
 * The remote peer's port, where there is one.
 */
remotePort: number | null, 
/**
 * `None` for UDP.
 */
state: SocketState | null, 
/**
 * The owning process, where the platform could attribute one.
 */
pid: number | null, 
/**
 * The owning process's name, where `pid` resolved against the process
 * table.
 */
processName: string | null, 
/**
 * The owning process's executable path, where it could be read.
 */
processPath: string | null, };
