// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessKey } from "./ProcessKey";
import type { ProcessRecord } from "./ProcessRecord";

/**
 * What changed between two ticks.
 *
 * `changed` is the field that decides whether this is a diff or a full snapshot
 * wearing a diff's name — see [`differs_on_screen`].
 */
export type ProcessDiff = { 
/**
 * Processes that were not in the previous tick.
 */
added: Array<ProcessRecord>, 
/**
 * Identities that were in the previous tick and are gone.
 *
 * Carries the full [`ProcessKey`] rather than a bare PID: when a PID is
 * recycled within one tick, the same number appears here as removed and in
 * `added` as a new process, and the start time is what tells them apart.
 */
removed: Array<ProcessKey>, 
/**
 * Processes whose displayed values moved.
 */
changed: Array<ProcessRecord>, };
