// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a process is currently doing.
 */
export type ProcessStatus = "running" | "sleeping" | "idle" | "stopped" | "zombie" | "unknown";
