// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The identity of a process.
 *
 * A PID alone is not enough. Operating systems reuse PIDs, and a tick that
 * treats a recycled PID as the same process will happily show the new process
 * inheriting the old one's children and history. The start time is what makes
 * this a real identity.
 */
export type ProcessKey = { 
/**
 * Process identifier.
 */
pid: number, 
/**
 * Seconds since the Unix epoch at which the process started.
 */
startedAt: number, };
