// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessStatus } from "./ProcessStatus";

/**
 * One process, as a platform reports it — flat, with no hierarchy.
 */
export type ProcessRecord = { 
/**
 * Process identifier.
 */
pid: number, 
/**
 * Parent's identifier, absent for a root.
 */
parentPid: number | null, 
/**
 * Executable name as shown in the tree.
 */
name: string, 
/**
 * Full path to the executable, where it could be read.
 */
exe: string | null, 
/**
 * Owning user, where it could be resolved.
 */
user: string | null, 
/**
 * CPU utilisation as a percentage. May exceed 100 on multi-core machines.
 */
cpu: number, 
/**
 * Resident memory in bytes.
 */
memory: number, 
/**
 * Bytes read per second during the last tick.
 */
diskReadRate: number, 
/**
 * Bytes written per second during the last tick.
 */
diskWriteRate: number, 
/**
 * Seconds since the Unix epoch at which the process started.
 */
startedAt: number, 
/**
 * What the process is currently doing.
 */
status: ProcessStatus, };
