// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessNode } from "./ProcessNode";
import type { Rollup } from "./Rollup";

/**
 * Every process on the machine, arranged by parentage.
 */
export type ProcessTree = { 
/**
 * Processes with no live parent, ordered by PID.
 */
roots: Array<ProcessNode>, 
/**
 * Every process on the machine, summed.
 */
total: Rollup, };
