// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessRecord } from "./ProcessRecord";
import type { Rollup } from "./Rollup";

/**
 * A process and its descendants.
 */
export type ProcessNode = { 
/**
 * This process.
 */
record: ProcessRecord, 
/**
 * Children, ordered by PID so the tree is stable between ticks.
 */
children: Array<ProcessNode>, 
/**
 * This process plus everything beneath it.
 */
rollup: Rollup, };
