// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The multimodal projector beside a vision model's weights.
 *
 * Deliberately not a [`ModelDownload`]: a projector has no quantization cell
 * of its own to occupy, is never offered as a download on its own, and its
 * publisher is by construction whoever published the model it accompanies.
 * Reusing the richer type would invite exactly the mistake of listing one in
 * the fit matrix.
 */
export type ProjectorDownload = { 
/**
 * Hugging Face repository. Held separately from the model's `repo`
 * because nothing guarantees a re-quantiser ships both in one place,
 * though for the pin that introduced this field they do coincide.
 */
repo: string, 
/**
 * File name within the repository.
 */
file: string, 
/**
 * SHA256 of the file, lowercase hex, on the same terms as the model's:
 * pinned here, and a mismatch aborts with no override.
 */
sha256: string, 
/**
 * Exact size in bytes, from the Hugging Face API. Counted into the
 * free-space check alongside the model, since both must land.
 */
sizeBytes: number, };
