// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of osstat's two verification tiers a file was fetched under.
 *
 * The distinction outlives the download, which is why it is recorded rather
 * than inferred: once the bytes are on disk nothing about them says whether
 * the hash they were checked against had been reviewed by a person. A model
 * list that showed both the same way would quietly retire a guarantee
 * SECURITY.md still makes.
 */
export type Provenance = "pinned" | "searched";
