// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One quantization level the calculator evaluates every model at.
 *
 * Bit widths are a property of the quantization scheme, not of any one
 * model — GGUF k-quants mix precisions across tensor types, so the figure
 * here is the commonly measured average, not an exact constant. That is why
 * this lives once per registry rather than being repeated on every
 * [`ModelEntry`].
 */
export type QuantLevel = { 
/**
 * Stable identifier matching the llama.cpp quantization name, e.g.
 * `Q4_K_M`.
 */
id: string, 
/**
 * What the UI shows for this level.
 */
label: string, 
/**
 * Average bits per weight, used to derive a file size from a parameter
 * count rather than storing an exact byte count nobody could verify.
 */
bitsPerWeight: number, 
/**
 * What this level trades off, for the explanation drawer.
 */
description: string, };
