// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A process's own cost plus that of everything beneath it.
 *
 * This is what a collapsed row displays. Without it, collapsing a busy subtree
 * would make its load vanish from the screen — the tree would be lying by
 * omission exactly when a user is hunting for what is eating their machine.
 */
export type Rollup = { 
/**
 * Summed CPU percentage.
 *
 * Accumulated as `f64` even though the platform reports `f32`, so that
 * summing a thousand processes does not drift.
 */
cpu: number, 
/**
 * Summed resident memory in bytes.
 */
memory: number, 
/**
 * Summed read rate in bytes per second.
 */
diskReadRate: number, 
/**
 * Summed write rate in bytes per second.
 */
diskWriteRate: number, 
/**
 * How many processes are counted, including the one this describes.
 */
processes: number, };
