// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an acquisition is progressing.
 */
export type RuntimeProgress = { 
/**
 * What is happening: `downloading`, `cudaRuntime`, or `verifying`.
 */
phase: string, 
/**
 * Bytes fetched so far in the current phase.
 */
downloadedBytes: number, 
/**
 * Bytes expected in the current phase, from the pinned manifest.
 */
totalBytes: number, };
