// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledRuntimeInfo } from "./InstalledRuntimeInfo";
import type { RuntimeOption } from "./RuntimeOption";

/**
 * What the runtime section of Settings needs, in one call.
 */
export type RuntimeStatus = { 
/**
 * Runtimes already on disk.
 */
installed: Array<InstalledRuntimeInfo>, 
/**
 * The artifact this machine would install by default.
 *
 * `None` only on a target upstream publishes nothing for.
 */
recommended: RuntimeOption | null, 
/**
 * The CUDA alternative, when one exists for this machine.
 *
 * A separate field rather than a different value of `recommended`, because
 * the UI's job here is to present a choice with its cost rather than to
 * have made it already: CUDA is 538–642 MB against Vulkan's 34 MB.
 */
cudaAlternative: RuntimeOption | null, 
/**
 * The upstream release every option comes from.
 */
upstreamTag: string, };
