// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One artifact the user could install, and what it would cost.
 */
export type RuntimeOption = { 
/**
 * The `runtimes.json` identifier.
 */
artifactId: string, 
/**
 * Human-readable backend name, such as `Vulkan`.
 */
backend: string, 
/**
 * Every byte that must be downloaded, including any companion archive.
 */
downloadBytes: number, };
