// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The multimodal projector a searched repository ships beside its weights.
 *
 * Deliberately not a second [`SearchResult`]: a projector is never offered as
 * a model of its own, carries no quantization cell, and has no publisher
 * distinct from the repository it came from. Reusing the richer type would
 * invite exactly the mistake this module now excludes — listing a projector
 * among the models, where downloading it yields a file no chat can load.
 *
 * It carries no `repo` either. The repository is by construction the parent
 * result's, and a second one would be a second place a download URL could be
 * assembled from — the thing ADR-012 rests on there not being.
 */
export type SearchProjector = { 
/**
 * The path of the projector within the repository.
 */
file: string, 
/**
 * The LFS oid, checked exactly as the weights' is. Same origin as the
 * file, so it detects a corrupted transfer and not a replaced upload.
 */
sha256: string, 
/**
 * What the projector weighs, as the API reports it.
 */
sizeBytes: number, };
