// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchProjector } from "./SearchProjector";

/**
 * One downloadable `.gguf` file a search turned up.
 *
 * Everything needed to fetch and verify it, and nothing that could be mistaken
 * for a fit verdict. See the module docs for why `size_bytes` is the only
 * figure here.
 */
export type SearchResult = { 
/**
 * The Hugging Face repository, as `owner/name`.
 */
repo: string, 
/**
 * The repository's owner, shown so a result names who uploaded it.
 */
publisher: string, 
/**
 * The path of the file within the repository.
 */
file: string, 
/**
 * What the file weighs, as the API reports it.
 */
sizeBytes: number, 
/**
 * The LFS oid, which for these files is the SHA256 the download is checked
 * against. Same origin as the file — see the module docs.
 */
sha256: string, 
/**
 * The quantization tag read off the file name, if it carries a known one.
 *
 * A label, never an input to any calculation.
 */
quantHint: string | null, 
/**
 * The multimodal projector this repository ships, on a vision model.
 *
 * Not a verdict and not an estimate — the same three facts every other
 * downloadable file here carries, read off the same tree listing. A
 * vision GGUF holds the language model only; the weights that turn an
 * image into tokens it can attend to live in a second file passed as
 * `--mmproj`, so a result downloaded without this one produces a model
 * that loads, answers text, and silently ignores every image.
 *
 * `None` is a text-only repository and is what nearly every result is.
 */
projector: SearchProjector | null, };
