// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the advisor makes of a searched file, having read its header.
 *
 * Every field comes out of [`osstat_chat::plan_launch`] or out of the header it
 * was given. Nothing here is derived from the file size and a quantization tag
 * — that guess is what ADR-008 names as the worst thing this feature could do,
 * and the reason it is not needed is that the header was read rather than
 * guessed at.
 */
export type SearchedFit = { 
/**
 * Layers that would be offloaded to the GPU — what `-ngl` would be given.
 */
gpuLayers: number, 
/**
 * The model's transformer block count, so a partial offload can be shown
 * as the fraction it is rather than as a bare number.
 */
blockCount: number, 
/**
 * The context window that would be allocated.
 */
contextLength: number, 
/**
 * Whether every layer fitted. `false` is a warning, never a refusal.
 */
fits: boolean, 
/**
 * Whether the KV-cache arithmetic rested on a derived head dimension.
 *
 * Travels for the same reason it does on [`crate::chat::ModelSession`]: a
 * derived figure is right for standard attention and wrong for models that
 * diverge, and a mis-sized cache is otherwise a mystery rather than a
 * diagnosis.
 */
headDimDerived: boolean, };
