// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SocketProtocol } from "./SocketProtocol";
import type { SocketState } from "./SocketState";

/**
 * One socket, as a platform reports it — before it is joined to a process.
 */
export type SocketRecord = { 
/**
 * TCP or UDP.
 */
protocol: SocketProtocol, 
/**
 * The local address this socket is bound to, as text (`"127.0.0.1"`,
 * `"::1"`).
 */
localAddress: string, 
/**
 * The local port this socket is bound to.
 */
localPort: number, 
/**
 * The remote peer's address, absent for UDP and for a TCP socket with no
 * peer — chiefly one still in `LISTEN`.
 */
remoteAddress: string | null, 
/**
 * The remote peer's port; present exactly when `remote_address` is.
 */
remotePort: number | null, 
/**
 * `None` for UDP, which has no connection state to report.
 */
state: SocketState | null, 
/**
 * Owning process identifiers. See the module docs for why this is a list
 * rather than a single optional PID.
 */
pids: Array<number>, };
