// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a TCP connection sits in its lifecycle.
 *
 * UDP is stateless — see [`SocketRecord::state`] — so this only ever
 * accompanies a [`SocketProtocol::Tcp`] record.
 */
export type SocketState = "closed" | "listen" | "synSent" | "synReceived" | "established" | "finWait1" | "finWait2" | "closeWait" | "closing" | "lastAck" | "timeWait" | "deleteTcb" | "unknown";
