// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rough tokens-per-second tier — a classification, not a measurement.
 *
 * Real throughput depends on the runtime, the quantization implementation,
 * memory bandwidth and thermal behaviour; ADR-008 is explicit that
 * presenting a heuristic as a measurement is the most damaging thing this
 * feature could do. This tier exists only so the UI can say "slower" rather
 * than a number nobody actually measured.
 */
export type SpeedTier = "fast" | "moderate" | "slow";
