// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a download is stopping, and therefore what becomes of the `.part`.
 *
 * The two share everything — the same channel, the same signal, the same
 * wind-down — and differ by **one line**, the removal of the partial file in
 * [`fetch`]. They are one enum rather than two mechanisms so that the
 * difference is visible in one place instead of being spread across two
 * near-identical code paths that could drift apart.
 *
 * It crosses to the webview because the difference outlives the stop: after a
 * pause the figure the bar reached still describes bytes on disk, and after a
 * cancel it describes bytes that are gone.
 */
export type Stop = "pause" | "cancel";
