// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuDescription } from "./CpuDescription";
import type { DiskDescription } from "./DiskDescription";
import type { InterfaceDescription } from "./InterfaceDescription";

/**
 * The identity of the machine osstat is running on.
 *
 * Fetched once per session rather than per tick. Everything here is either
 * constant or changes on a human timescale.
 */
export type SystemDescription = { 
/**
 * Machine hostname.
 */
hostName: string | null, 
/**
 * Long OS name, e.g. `Windows 11 Home`.
 */
osName: string | null, 
/**
 * OS version or build, e.g. `26200`.
 */
osVersion: string | null, 
/**
 * Kernel version.
 */
kernelVersion: string | null, 
/**
 * Seconds since boot.
 */
uptimeSeconds: number, 
/**
 * The installed CPU.
 */
cpu: CpuDescription, 
/**
 * Total physical memory in bytes.
 */
totalMemory: number, 
/**
 * Total swap in bytes.
 */
totalSwap: number, 
/**
 * Mounted filesystems, in the order per-tick samples index them.
 */
disks: Array<DiskDescription>, 
/**
 * Network interfaces, in the order per-tick samples index them.
 */
interfaces: Array<InterfaceDescription>, };
