// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a termination did not happen.
 */
export type TerminationError = { 
/**
 * What went wrong, in a sentence the user can act on.
 */
message: string, 
/**
 * Whether elevation could plausibly help.
 *
 * ADR-006's signal. Nothing elevates yet, so the UI uses it only to
 * explain *why* it cannot help rather than to offer a prompt.
 */
permissionDenied: boolean, 
/**
 * Whether the PID was reused by a different process.
 *
 * Distinct from a permission failure because nothing was signalled and
 * retrying is pointless — the process the user selected has already gone.
 */
identityMismatch: boolean, };
