// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generation speeds, as `llama-server` reports them.
 *
 * Same two-spelling arrangement as [`Usage`], and for the same reason: these
 * figures are read off the wire and shown in the UI.
 */
export type Timings = { 
/**
 * Prompt processing rate. Absent until the prompt has been evaluated.
 */
promptPerSecond: number | null, 
/**
 * Generation rate. Absent until at least one token has been produced.
 */
predictedPerSecond: number | null, };
