// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the front end is reporting, as a fixed vocabulary.
 *
 * An enum rather than a string for the reason the whole module exists: a
 * string parameter is somewhere a page title or a message could be put.
 */
export type UiEventKind = "ready" | "pageChanged" | "settingChanged" | "commandFailed";
