// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token counts for one exchange.
 *
 * `Serialize` as well as `Deserialize`: these counts are read off the wire,
 * then stored with the message they belong to and shown in the UI.
 * Written in camelCase and read in either case. Everything crossing the IPC
 * boundary is camelCase (ADR-002), but `llama-server` writes `snake_case` on the
 * wire — so the alias accepts the server's spelling without making the webview
 * the one type that speaks differently from every other payload. The aliases
 * also mean conversations stored before this rename still load.
 */
export type Usage = { 
/**
 * Tokens in the prompt, including the whole conversation so far.
 */
promptTokens: number, 
/**
 * Tokens generated in reply.
 */
completionTokens: number, };
