// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three verdict shapes ADR-008 names: fits in VRAM, fits with CPU
 * offload, or will not run — plus the CPU-only case a machine with no GPU
 * produces, which the ADR groups under "fits with offload" in prose but
 * which this calculator gives its own tag because there is no GPU to
 * offload *from*.
 */
export type VerdictKind = "fitsOnGpu" | "fitsWithCpuOffload" | "fitsOnCpuOnly" | "wontFit";
