// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeedTier } from "./SpeedTier";
import type { VerdictKind } from "./VerdictKind";

/**
 * The verdict for one model at one quantization level.
 */
export type Verdict = { 
/**
 * Which of the four shapes this is.
 */
kind: VerdictKind, 
/**
 * Layers estimated to stay resident on the GPU. Always `num_layers` for
 * [`VerdictKind::FitsOnGpu`] and `0` for anything with no usable GPU.
 */
gpuLayers: number, 
/**
 * Layers estimated to run on the CPU instead. `gpu_layers + cpu_layers`
 * always equals the model's layer count.
 */
cpuLayers: number, 
/**
 * A rough speed classification — see [`SpeedTier`].
 */
tier: SpeedTier, };
