//! The IPC surface exposed to the webview.
//!
//! Every command is a thin adapter: it borrows types from `osstat-core` /
//! `osstat-platform`, does no system work itself, and returns a `serde`
//! type whose TypeScript mirror is generated by `ts-rs` (ADR-002). Commands
//! declared here are callable only through the allow-list built by
//! [`tauri::generate_handler!`] in [`crate::run`].

// Tauri resolves managed state by injecting `State<'_, T>` by value; a
// reference is not part of the command signature it accepts. The guard is a
// cheap handle, so the lint's concern does not apply here.
#![allow(clippy::needless_pass_by_value)]

use std::time::Duration;

use osstat_core::{
    BuildInfo, GpuDevice, MetricsSample, PortRecord, ProcessRecord, SystemDescription,
};
use osstat_llm::calculator::{FitResult, GpuBudget, compute_fit_matrix, select_gpu_budget};
use osstat_llm::registry::{ModelRegistry, seeded_registry};
use osstat_platform::PlatformId;
use serde::Serialize;
use tauri::State;

use crate::ports::PortInspector;
use crate::sampler::Sampler;
use crate::window_state::{CloseBehaviour, CloseSetting};

/// Identity of the running application: what it is, and what it is running on.
///
/// This is the payload behind the About panel and the "copy for a bug report"
/// action, so it is intentionally cheap to produce and free of anything that
/// could fail.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[cfg_attr(feature = "ts-bindings", derive(ts_rs::TS))]
#[cfg_attr(feature = "ts-bindings", ts(export))]
#[serde(rename_all = "camelCase")]
pub struct AppInfo {
    /// Name, version and profile of this build.
    pub build: BuildInfo,
    /// Machine-readable identifier of the host platform.
    pub platform: PlatformId,
    /// How users of the host platform normally spell its name.
    pub platform_name: String,
}

impl AppInfo {
    /// Collects the identity of the currently running binary.
    #[must_use]
    pub fn current() -> Self {
        Self {
            // Read from this crate rather than `osstat-core` so the reported
            // name and version describe the shipped app, not the library.
            build: BuildInfo::new(env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION")),
            platform: osstat_platform::current(),
            platform_name: osstat_platform::display_name().to_owned(),
        }
    }
}

/// Returns the identity of the running application.
#[tauri::command]
#[must_use]
pub fn app_info() -> AppInfo {
    AppInfo::current()
}

/// Returns the machine's identity: OS, CPU, disks and interfaces.
///
/// Read once at startup, so this is a clone of stored data rather than a fresh
/// interrogation of the system.
#[tauri::command]
#[must_use]
pub fn system_description(sampler: State<'_, Sampler>) -> SystemDescription {
    sampler.description().clone()
}

/// Returns recent metric samples, oldest first.
///
/// `limit` bounds how many are returned. The history lives in Rust precisely so
/// that a chart can paint filled on its very first render instead of growing in
/// from an empty axis after a reload.
#[tauri::command]
#[must_use]
pub fn metrics_history(sampler: State<'_, Sampler>, limit: Option<u32>) -> Vec<MetricsSample> {
    sampler.history(limit.map(|limit| limit as usize))
}

/// Returns every process from the most recent tick, flat and unordered.
///
/// This is the front-end's starting snapshot; from then on it applies the
/// `processes:tick` diffs to what it already holds.
#[tauri::command]
#[must_use]
pub fn process_list(sampler: State<'_, Sampler>) -> Vec<ProcessRecord> {
    sampler.processes()
}

/// Returns every socket currently open, joined to the process that holds it.
///
/// Read fresh on every call rather than cached: unlike the process table this
/// is not on the sampler's tick, so "fresh" here means "as of this call",
/// which is what a page a user opens to check one specific port wants.
#[tauri::command]
#[must_use]
pub fn port_list(sampler: State<'_, Sampler>, ports: State<'_, PortInspector>) -> Vec<PortRecord> {
    ports.list(&sampler.processes())
}

/// Returns the GPUs found, or `None` while the probe is still running.
///
/// `None` and `Some([])` mean different things and the UI distinguishes them:
/// "still looking" versus "there is no GPU in this machine".
#[tauri::command]
#[must_use]
pub fn gpu_devices(sampler: State<'_, Sampler>) -> Option<Vec<GpuDevice>> {
    sampler.devices()
}

/// The narrowest context length the advisor will weigh a model at.
///
/// Below this the KV-cache term is too small to change any verdict, so a
/// smaller figure would only produce a table that looks more optimistic
/// than any real use of the model would be.
const MIN_CONTEXT_LENGTH: u32 = 512;

/// The widest context length the advisor will weigh a model at.
///
/// A megatoken is beyond every model in the seed registry; the per-model
/// cap the UI actually enforces is `architecture.max_context_length`, and
/// this is only the backstop that keeps the KV-cache arithmetic away from
/// figures no model could accept.
const MAX_CONTEXT_LENGTH: u32 = 1_048_576;

/// Brings a requested context length inside the range the arithmetic is
/// meaningful over.
///
/// Split out from [`llm_advice`] so the clamp is testable without a running
/// Tauri app and its managed [`Sampler`] state.
const fn clamped_context_length(requested: u32) -> u32 {
    if requested < MIN_CONTEXT_LENGTH {
        MIN_CONTEXT_LENGTH
    } else if requested > MAX_CONTEXT_LENGTH {
        MAX_CONTEXT_LENGTH
    } else {
        requested
    }
}

/// The whole advisor answer for one machine at one context length.
///
/// The hardware card and the fit matrix are one payload rather than two
/// commands because they have to agree: a matrix computed against a GPU
/// budget the card is not showing is a table whose arithmetic the user
/// cannot check, which is exactly what ADR-008 asks this feature not to be.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[cfg_attr(feature = "ts-bindings", derive(ts_rs::TS))]
#[cfg_attr(feature = "ts-bindings", ts(export))]
#[serde(rename_all = "camelCase")]
pub struct LlmAdvice {
    /// The VRAM the matrix was weighed against.
    pub gpu: GpuBudget,
    /// The system memory the matrix was weighed against.
    #[cfg_attr(feature = "ts-bindings", ts(type = "number"))]
    pub system_memory_bytes: u64,
    /// The context length actually used, after clamping.
    pub context_length: u32,
    /// One row per model per quantization level.
    pub results: Vec<FitResult>,
}

/// Returns the seed model registry: the quantization levels and the models.
///
/// Static data embedded in the binary, so this is a clone rather than a read
/// of anything — the UI holds it to label the fit matrix's rows and columns.
#[tauri::command]
#[must_use]
pub fn model_registry() -> ModelRegistry {
    seeded_registry()
}

/// Weighs every model at every quantization against this machine.
///
/// Returns `None` while the GPU probe is still running, exactly as
/// [`gpu_devices`] does and for the same reason: a matrix computed before
/// the probe answers would report "no GPU" on a machine that has one, and a
/// confident wrong verdict is the failure mode ADR-008 cares most about.
/// Once the probe finishes it emits `gpus:ready`, which is the front end's
/// cue to ask again.
///
/// `context_length` is clamped rather than rejected, following
/// [`set_sample_interval`]; the clamped figure travels back in
/// [`LlmAdvice::context_length`] so the drawer shows the number the
/// arithmetic actually used.
#[tauri::command]
#[must_use]
pub fn llm_advice(sampler: State<'_, Sampler>, context_length: u32) -> Option<LlmAdvice> {
    let devices = sampler.devices()?;
    let context_length = clamped_context_length(context_length);
    let gpu = select_gpu_budget(&devices);
    let system_memory_bytes = sampler.description().total_memory;

    Some(LlmAdvice {
        gpu,
        system_memory_bytes,
        context_length,
        results: compute_fit_matrix(&seeded_registry(), context_length, gpu, system_memory_bytes),
    })
}

/// Sets how often the sampler ticks, in milliseconds.
///
/// Out-of-range values are clamped rather than rejected — see
/// [`Sampler::set_interval`].
#[tauri::command]
pub fn set_sample_interval(sampler: State<'_, Sampler>, millis: u32) {
    sampler.set_interval(Duration::from_millis(u64::from(millis)));
}

/// Suspends or resumes sampling.
#[tauri::command]
pub fn set_sampling_paused(sampler: State<'_, Sampler>, paused: bool) {
    sampler.set_paused(paused);
}

/// Sets what closing the window does.
///
/// Held in Rust because `CloseRequested` must be answered synchronously; see
/// [`crate::window_state`].
#[tauri::command]
pub fn set_close_behaviour(setting: State<'_, CloseSetting>, behaviour: CloseBehaviour) {
    setting.set(behaviour);
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    #[test]
    fn reports_the_app_package_not_the_core_library() {
        let info = AppInfo::current();
        assert_eq!(info.build.name, "osstat");
        assert!(!info.build.version.is_empty());
    }

    #[test]
    fn reports_the_compiled_platform() {
        assert_eq!(AppInfo::current().platform, osstat_platform::current());
    }

    #[test]
    fn platform_name_is_human_readable() {
        assert!(!AppInfo::current().platform_name.is_empty());
    }

    #[test]
    fn command_matches_the_constructor() {
        assert_eq!(app_info(), AppInfo::current());
    }

    #[test]
    fn the_seed_registry_reaches_the_ipc_surface_populated() {
        let registry = model_registry();
        assert!(
            !registry.models.is_empty(),
            "the advisor has nothing to advise about"
        );
        assert!(
            !registry.quant_levels.is_empty(),
            "the fit matrix would have no columns"
        );
    }

    #[test]
    fn a_context_length_inside_the_range_is_left_alone() {
        assert_eq!(clamped_context_length(4096), 4096);
        assert_eq!(
            clamped_context_length(MIN_CONTEXT_LENGTH),
            MIN_CONTEXT_LENGTH
        );
        assert_eq!(
            clamped_context_length(MAX_CONTEXT_LENGTH),
            MAX_CONTEXT_LENGTH
        );
    }

    #[test]
    fn a_context_length_below_the_range_is_raised_not_rejected() {
        assert_eq!(clamped_context_length(0), MIN_CONTEXT_LENGTH);
        assert_eq!(clamped_context_length(1), MIN_CONTEXT_LENGTH);
    }

    #[test]
    fn a_context_length_above_the_range_is_capped_not_rejected() {
        assert_eq!(clamped_context_length(u32::MAX), MAX_CONTEXT_LENGTH);
    }

    #[test]
    fn every_model_is_priced_at_every_quantization_level() {
        let registry = model_registry();
        let matrix = osstat_llm::calculator::compute_fit_matrix(
            &registry,
            4096,
            GpuBudget::absent(),
            32 * 1024 * 1024 * 1024,
        );
        assert_eq!(
            matrix.len(),
            registry.models.len() * registry.quant_levels.len()
        );
    }

    #[test]
    fn advice_serialises_the_arithmetic_the_drawer_needs() {
        let advice = LlmAdvice {
            gpu: GpuBudget::absent(),
            system_memory_bytes: 16 * 1024 * 1024 * 1024,
            context_length: 4096,
            results: Vec::new(),
        };
        let json = serde_json::to_value(&advice).unwrap();
        let object = json.as_object().unwrap();
        assert!(object.contains_key("systemMemoryBytes"));
        assert!(object.contains_key("contextLength"));
        assert!(object.contains_key("results"));
        assert!(object.contains_key("gpu"));
    }

    #[test]
    fn serialises_nested_fields_as_camel_case() {
        let json = serde_json::to_value(AppInfo::current()).unwrap();
        let object = json.as_object().unwrap();
        assert!(object.contains_key("platformName"));
        assert!(object.contains_key("build"));
        assert!(object.contains_key("platform"));
    }
}
