//! The IPC surface exposed to the webview.
//!
//! Every command is a thin adapter: it borrows types from `osstat-core` /
//! `osstat-platform`, does no system work itself, and returns a `serde`
//! type whose TypeScript mirror is generated by `ts-rs` (ADR-002). Commands
//! declared here are callable only through the allow-list built by
//! [`tauri::generate_handler!`] in [`crate::run`].

use osstat_core::BuildInfo;
use osstat_platform::PlatformId;
use serde::Serialize;

/// Identity of the running application: what it is, and what it is running on.
///
/// This is the payload behind the About panel and the "copy for a bug report"
/// action, so it is intentionally cheap to produce and free of anything that
/// could fail.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[cfg_attr(feature = "ts-bindings", derive(ts_rs::TS))]
#[cfg_attr(
    feature = "ts-bindings",
    ts(export, export_to = "../../ui/src/bindings/")
)]
#[serde(rename_all = "camelCase")]
pub struct AppInfo {
    /// Name, version and profile of this build.
    pub build: BuildInfo,
    /// Machine-readable identifier of the host platform.
    pub platform: PlatformId,
    /// How users of the host platform normally spell its name.
    pub platform_name: String,
}

impl AppInfo {
    /// Collects the identity of the currently running binary.
    #[must_use]
    pub fn current() -> Self {
        Self {
            // Read from this crate rather than `osstat-core` so the reported
            // name and version describe the shipped app, not the library.
            build: BuildInfo::new(env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION")),
            platform: osstat_platform::current(),
            platform_name: osstat_platform::display_name().to_owned(),
        }
    }
}

/// Returns the identity of the running application.
#[tauri::command]
#[must_use]
pub fn app_info() -> AppInfo {
    AppInfo::current()
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    #[test]
    fn reports_the_app_package_not_the_core_library() {
        let info = AppInfo::current();
        assert_eq!(info.build.name, "osstat");
        assert!(!info.build.version.is_empty());
    }

    #[test]
    fn reports_the_compiled_platform() {
        assert_eq!(AppInfo::current().platform, osstat_platform::current());
    }

    #[test]
    fn platform_name_is_human_readable() {
        assert!(!AppInfo::current().platform_name.is_empty());
    }

    #[test]
    fn command_matches_the_constructor() {
        assert_eq!(app_info(), AppInfo::current());
    }

    #[test]
    fn serialises_nested_fields_as_camel_case() {
        let json = serde_json::to_value(AppInfo::current()).unwrap();
        let object = json.as_object().unwrap();
        assert!(object.contains_key("platformName"));
        assert!(object.contains_key("build"));
        assert!(object.contains_key("platform"));
    }
}
