//! The IPC surface exposed to the webview.
//!
//! Every command is a thin adapter: it borrows types from `osstat-core` /
//! `osstat-platform`, does no system work itself, and returns a `serde`
//! type whose TypeScript mirror is generated by `ts-rs` (ADR-002). Commands
//! declared here are callable only through the allow-list built by
//! [`tauri::generate_handler!`] in [`crate::run`].

// Tauri resolves managed state by injecting `State<'_, T>` by value; a
// reference is not part of the command signature it accepts. The guard is a
// cheap handle, so the lint's concern does not apply here.
#![allow(clippy::needless_pass_by_value)]

use std::time::Duration;

use osstat_core::{BuildInfo, GpuDevice, MetricsSample, ProcessRecord, SystemDescription};
use osstat_platform::PlatformId;
use serde::Serialize;
use tauri::State;

use crate::sampler::Sampler;
use crate::window_state::{CloseBehaviour, CloseSetting};

/// Identity of the running application: what it is, and what it is running on.
///
/// This is the payload behind the About panel and the "copy for a bug report"
/// action, so it is intentionally cheap to produce and free of anything that
/// could fail.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[cfg_attr(feature = "ts-bindings", derive(ts_rs::TS))]
#[cfg_attr(feature = "ts-bindings", ts(export))]
#[serde(rename_all = "camelCase")]
pub struct AppInfo {
    /// Name, version and profile of this build.
    pub build: BuildInfo,
    /// Machine-readable identifier of the host platform.
    pub platform: PlatformId,
    /// How users of the host platform normally spell its name.
    pub platform_name: String,
}

impl AppInfo {
    /// Collects the identity of the currently running binary.
    #[must_use]
    pub fn current() -> Self {
        Self {
            // Read from this crate rather than `osstat-core` so the reported
            // name and version describe the shipped app, not the library.
            build: BuildInfo::new(env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION")),
            platform: osstat_platform::current(),
            platform_name: osstat_platform::display_name().to_owned(),
        }
    }
}

/// Returns the identity of the running application.
#[tauri::command]
#[must_use]
pub fn app_info() -> AppInfo {
    AppInfo::current()
}

/// Returns the machine's identity: OS, CPU, disks and interfaces.
///
/// Read once at startup, so this is a clone of stored data rather than a fresh
/// interrogation of the system.
#[tauri::command]
#[must_use]
pub fn system_description(sampler: State<'_, Sampler>) -> SystemDescription {
    sampler.description().clone()
}

/// Returns recent metric samples, oldest first.
///
/// `limit` bounds how many are returned. The history lives in Rust precisely so
/// that a chart can paint filled on its very first render instead of growing in
/// from an empty axis after a reload.
#[tauri::command]
#[must_use]
pub fn metrics_history(sampler: State<'_, Sampler>, limit: Option<u32>) -> Vec<MetricsSample> {
    sampler.history(limit.map(|limit| limit as usize))
}

/// Returns every process from the most recent tick, flat and unordered.
///
/// This is the front-end's starting snapshot; from then on it applies the
/// `processes:tick` diffs to what it already holds.
#[tauri::command]
#[must_use]
pub fn process_list(sampler: State<'_, Sampler>) -> Vec<ProcessRecord> {
    sampler.processes()
}

/// Returns the GPUs found, or `None` while the probe is still running.
///
/// `None` and `Some([])` mean different things and the UI distinguishes them:
/// "still looking" versus "there is no GPU in this machine".
#[tauri::command]
#[must_use]
pub fn gpu_devices(sampler: State<'_, Sampler>) -> Option<Vec<GpuDevice>> {
    sampler.devices()
}

/// Sets how often the sampler ticks, in milliseconds.
///
/// Out-of-range values are clamped rather than rejected — see
/// [`Sampler::set_interval`].
#[tauri::command]
pub fn set_sample_interval(sampler: State<'_, Sampler>, millis: u32) {
    sampler.set_interval(Duration::from_millis(u64::from(millis)));
}

/// Suspends or resumes sampling.
#[tauri::command]
pub fn set_sampling_paused(sampler: State<'_, Sampler>, paused: bool) {
    sampler.set_paused(paused);
}

/// Sets what closing the window does.
///
/// Held in Rust because `CloseRequested` must be answered synchronously; see
/// [`crate::window_state`].
#[tauri::command]
pub fn set_close_behaviour(setting: State<'_, CloseSetting>, behaviour: CloseBehaviour) {
    setting.set(behaviour);
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    #[test]
    fn reports_the_app_package_not_the_core_library() {
        let info = AppInfo::current();
        assert_eq!(info.build.name, "osstat");
        assert!(!info.build.version.is_empty());
    }

    #[test]
    fn reports_the_compiled_platform() {
        assert_eq!(AppInfo::current().platform, osstat_platform::current());
    }

    #[test]
    fn platform_name_is_human_readable() {
        assert!(!AppInfo::current().platform_name.is_empty());
    }

    #[test]
    fn command_matches_the_constructor() {
        assert_eq!(app_info(), AppInfo::current());
    }

    #[test]
    fn serialises_nested_fields_as_camel_case() {
        let json = serde_json::to_value(AppInfo::current()).unwrap();
        let object = json.as_object().unwrap();
        assert!(object.contains_key("platformName"));
        assert!(object.contains_key("build"));
        assert!(object.contains_key("platform"));
    }
}
